# cargo-deny configuration for MonKey
# Hardware safety, license compliance, and security advisory auditing.

[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-workspace = true
skip = [
    "miniz_oxide",
    "syn",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
